### PR TITLE
Bump Version to use Default Config

### PR DESCRIPTION
**Pull request by alan20854**

### CODE REVIEW

**Comment by alan20854** [comment]
HOLD until open api bug fixed

**Comment by alan20854** [comment]
> HOLD until open api bug fixed

fixed

**Comment by alan20854** [comment]
Default config working correctly, as you can see in commit hash `ff97492`, where there is no config given

**Review by henkejosh — APPROVED** [review]
don't forget to make a new action release too :)

**Comment by henkejosh** [comment]
> don't forget to make a new action release too :)

and actually should we include README updates for the changes here?

**Comment by alan20854** [comment]
> > don't forget to make a new action release too :)
> 
> and actually should we include README updates for the changes here?

yea I can add a section on this pr

**Review by henkejosh — APPROVED** [review]

**Pull request merged**
